---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  directories:
    - $HOME/.node

before_install:
  - npm config set spin false

install:
  - npm install

script:
  - npm test

notifications:
  email: false
  slack:
    secure: "pWLL9PcHGn01QUyX8Xi3q/7iA+Zod9Pv9bGwTRfQzL6XYNuino12WNJiTX9g5CXGInhJENCfzt6podJ8dN7gW08OWQCE8GUJHZ4cETPoO8BY4dC8YADUDHn0eP47NKtGrsVCMj0+KxQzCBhwL3bMG9GvmVPrA+J+BENwAIJt3lY="

deploy:
  provider: npm
  email: me@tomasbasham.co.uk
  api_key:
    secure: "YgG6OVlYkHCj9adO2JeZZms8qg/qJY3lDS0o12CORfFCGAmiwZc1XVcKD8MzKDuG4bCmZxSf0E4078Pkxg9GqzPg5YpyU7GOq37BeSxagoxZyT6cPIB04Pm9WZsrIe3T4xvFsmJpyMZuM+nHbgfO0netw5qf8r81otvMN6XXOck="
  on:
    tags: true
    repo: tomasbasham/conical
