---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  directories:
    - $HOME/.node

before_install:
  - npm config set spin false

install:
  - npm install

script:
  - npm test

notifications:
  email: false
  slack:
    secure: "pWLL9PcHGn01QUyX8Xi3q/7iA+Zod9Pv9bGwTRfQzL6XYNuino12WNJiTX9g5CXGInhJENCfzt6podJ8dN7gW08OWQCE8GUJHZ4cETPoO8BY4dC8YADUDHn0eP47NKtGrsVCMj0+KxQzCBhwL3bMG9GvmVPrA+J+BENwAIJt3lY="

deploy:
  provider: npm
  email: me@tomasbasham.co.uk
  skip_cleanup: true
  api_key:
    secure: "vMLMnCzp53tDY3EA0R47hTtVyvOPQ6Ad+99ozFIzGK2k03oYmd+RKgsNrXzEZe7EqjoC4vl9XRRRhSZrggK2sFjlDP/+0SaIzoRsahsQ+9J/21ZIEo2iNzWmuEAZTNkyvGAgK9l2zr6pIq8cjhmVkjbddYa8fcTVQMe2sAF5buM="
  on:
    tags: true
    repo: tomasbasham/conical
